### PR TITLE
feat: remove endpoint label in title and search with enter

### LINKED ISSUE #208: Improve Subjects searchbar UI
**Is your feature request related to a problem? Please describe.**
We added a new UI for aind-metadata-service with searchbars for the Subject endpoint to start. @sharmishtaa had a few suggestions to improve the UI.

**Describe the solution you'd like**
1. Make endpoint label in title less confusing. Currently it shows as `/subject/{subject_id}` and looks like it may be selectable. Change it to explicitly show that is the endpoint, or remove it.
2. Allow users to submit by pressing enter.
3. Put `Data` before `Message` (so that validation errors are shown after the actual data json)
4. Consider not highlighting certain error responses in red (e.g. if there is data but returns 406 because of validation errors)

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by micahwoodard**
fixes #208 
- remove endpoint label in title 
- use enter to search  
- display data before message

### CODE REVIEW

**Comment by micahwoodard** [comment]
Do we want to remove highlight for metadata that has validation errors?

**Comment by helen-m-lin** [comment]
> Do we want to remove highlight for metadata that has validation errors?

Maybe we should add a check so that certain error codes are red-highlighted. We can probably leave the success ones as is. Looking at these, I think 406 and 300 do not need to be red highlighted, @jtyoung84 what do you think?

https://github.com/AllenNeuralDynamics/aind-metadata-service/blob/52e593cc6fe4510c99c34903ce86146e7762ce6e/src/aind_metadata_service/client.py#L8-L18

**Comment by jtyoung84** [comment]
> > Do we want to remove highlight for metadata that has validation errors?
> 
> Maybe we should add a check so that certain error codes are red-highlighted. We can probably leave the success ones as is. Looking at these, I think 406 and 300 do not need to be red highlighted, @jtyoung84 what do you think?
> 
> https://github.com/AllenNeuralDynamics/aind-metadata-service/blob/52e593cc6fe4510c99c34903ce86146e7762ce6e/src/aind_metadata_service/client.py#L8-L18

We probably don't need to highlight them.

**Comment by micahwoodard** [comment]
Okay makes sense to me! Here is a version where if the status code is 406 or 300, the text is just black. Where you thinking of just having the text in black or be in another color like green or darkorange?

**Review by jtyoung84 — APPROVED** [review]

**Pull request merged**
